# Config files

include ../Makefile.inc

CONFIG_FILES = $(wildcard *.xml)

all:
	@echo "Nothing to do here.."

clean:
	@echo "Nothing to do here.."

install:
	@mkdir -p ${INSTALL_DIR}
	@echo "Copying in ${INSTALL_DIR}"
	@cp ${CONFIG_FILES} ${INSTALL_DIR}
